- name: Incrementally install stuff to diagnose
  hosts: n100
  tasks:
  - name: Update and upgrade apt packages
    become: true
    apt:
      upgrade: yes
      update_cache: yes
      cache_valid_time: 86400
  - name: Install a few things
    become: true
    apt:
      update_cache: yes
      cache_valid_time: 86400
      name:
        - minidlna
        - openseachest
        - powertop
        - samba
  # Bear in mind that no effort was made to find the right path for the Realtek NIC
  # Also blindly running powertop --auto-tune might not be such a good idea. Perhaps
  # it would be better to apply the different settings one by one
  - name: Do some power optimizations
    become: true
    ansible.builtin.shell: powertop --auto-tune && echo 1 >> /sys/bus/pci/drivers/r8169/0000\:02\:00.0/link/l1_aspm
